### ISSUE TITLE
CircleCI Failure Message Resolution?

### ISSUE THREAD

**Issue by mrmundt** [conda-forge/pyomo-feedstock#73]
### Comment:

We recently started getting CircleCI failure messages with the general error: ` Could not find a usable config.yml, you may have revoked the CircleCI OAuth App.` CircleCI has never run before, so we're not sure what to do to resolve this.

@ngam - You've helped us in the past. Have you seen this error before, and if so, how do we resolve it?

**Comment by ngam** [comment]
> @ngam - You've helped us in the past. Have you seen this error before, and if so, how do we resolve it?

Yes, I've seen it before. I wouldn't worry about it since conda-forge doesn't really use CircleCI anymore. I believe it was an error in the automated configuration that ended up sporadically triggering CircleCI build attempts in many feedstocks.

It seems that https://github.com/conda-forge/pyomo-feedstock/pull/74 is working as expected so the issue is hopefully resolved now.
